title: Manish Gupta
logo: "/images/Manish.png" 
description: > 
  Principal Consultant at Wipro Limited 
  <br><br>    
  Data Scientist | ML | DL | AI | NLP | GenAI
  <br><br>
  Email: <a href="mgupta.power@gmail.com">mgupta.power@gmail.com</a>
  <br><br>
  <a href="https://www.linkedin.com/in/manishguptaind/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://public.tableau.com/app/profile/manishgupta.bi">View My Tableau Profile</a>
  <br><br>
  <a href="https://www.kaggle.com/manishguptads">View My Kaggle Profile</a>
  <br><br>
  <a href="https://manish-gupta.medium.com/">Read my articles on Medium</a>

  
theme: jekyll-theme-minimal
