title: Manish Gupta
logo: "/images/Manish.png" 
description: > 
  Learner at Simplilearn-Purdue University 
  <br><br>    
  Data Scientist | ML | DL | AI 
  <br><br>
  Email: <a href="mgupta.power@gmail.com">mgupta.power@gmail.com</a>
  <br><br>
  <a href="https://www.linkedin.com/in/manish4gupta/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://www.kaggle.com/manishguptads">View My Kaggle Profile</a>

  
theme: jekyll-theme-minimal
google_analytics: G-X6682SKESS
