title: Manish Gupta
logo: "/images/manish.png?raw=true" 
description: > 
  Learner at Simplilearn-Purdue University 
  <br><br>
  Data Scientist | ML | DL | AI 
  <br><br>
  <a href="https://www.linkedin.com/in/manish4gupta/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
